#!/usr/bin/env bash
#SBATCH --job-name=rime_rnaseq          # Job name
#SBATCH --nodes=1                       # Number of nodes to run on 
#SBATCH --ntasks=1                      # Number of MPI tasks to request
#SBATCH --cpus-per-task=1               # Number of CPU cores per MPI task
#SBATCH --mem=16G                       # Total memory to request
#SBATCH --time=1-00:00:00               # Time limit (DD-HH:MM:SS)
#SBATCH --account=biol-student-2023     # Project account to use
#SBATCH --mail-type=ALL                 # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=as3800@york.ac.uk   # Where to send mail
#SBATCH --output=%x-%j.log              # Standard output log
#SBATCH --error=%x-%j.err               # Standard error log
#SBATCH --partition=nodes

# Abort if any command fails
set -e

# Purge any previously loaded modules #
module purge

# Load modules #
module load R/4.2.1-foss-2022a
module load R-bundle-Bioconductor/3.18-foss-2023a-R-4.3.2
# Commands to run #
Rscript gr_script.R

